name: generate snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: rajanchamp98
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
